/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[playerid][1];
new Text:PublicTD[playerid][5];
new Text:PublicTD[playerid][6];
new Text:PublicTD[playerid][7];
new Text:PublicTD[playerid][9];
new Text:PublicTD[playerid][12];

//Textdraws
PublicTD[playerid][1] = TextDrawCreate(320.000000, 80.000000, "Vive tu vida");
TextDrawFont(PublicTD[playerid][1], 1);
TextDrawLetterSize(PublicTD[playerid][1], 0.500000, 2.500000);
TextDrawTextSize(PublicTD[playerid][1], 0.000000, 640.000000);
TextDrawSetOutline(PublicTD[playerid][1], 1);
TextDrawSetShadow(PublicTD[playerid][1], 1);
TextDrawAlignment(PublicTD[playerid][1], 2);
TextDrawColor(PublicTD[playerid][1], 12582911);
TextDrawBackgroundColor(PublicTD[playerid][1], 255);
TextDrawBoxColor(PublicTD[playerid][1], 50);
TextDrawUseBox(PublicTD[playerid][1], 0);
TextDrawSetProportional(PublicTD[playerid][1], 1);
TextDrawSetSelectable(PublicTD[playerid][1], 0);

PublicTD[playerid][5] = TextDrawCreate(320.000000, 160.000000, "BIENVENIDO");
TextDrawFont(PublicTD[playerid][5], 2);
TextDrawLetterSize(PublicTD[playerid][5], 0.216665, 1.049998);
TextDrawTextSize(PublicTD[playerid][5], 0.000000, 640.000000);
TextDrawSetOutline(PublicTD[playerid][5], 1);
TextDrawSetShadow(PublicTD[playerid][5], 0);
TextDrawAlignment(PublicTD[playerid][5], 2);
TextDrawColor(PublicTD[playerid][5], 12582911);
TextDrawBackgroundColor(PublicTD[playerid][5], 255);
TextDrawBoxColor(PublicTD[playerid][5], 50);
TextDrawUseBox(PublicTD[playerid][5], 0);
TextDrawSetProportional(PublicTD[playerid][5], 1);
TextDrawSetSelectable(PublicTD[playerid][5], 0);

PublicTD[playerid][6] = TextDrawCreate(320.000000, 200.000000, "~n~~n~");
TextDrawFont(PublicTD[playerid][6], 1);
TextDrawLetterSize(PublicTD[playerid][6], 0.000000, 0.000000);
TextDrawTextSize(PublicTD[playerid][6], 0.000000, 640.000000);
TextDrawSetOutline(PublicTD[playerid][6], 0);
TextDrawSetShadow(PublicTD[playerid][6], 0);
TextDrawAlignment(PublicTD[playerid][6], 2);
TextDrawColor(PublicTD[playerid][6], -1);
TextDrawBackgroundColor(PublicTD[playerid][6], 255);
TextDrawBoxColor(PublicTD[playerid][6], 50);
TextDrawUseBox(PublicTD[playerid][6], 0);
TextDrawSetProportional(PublicTD[playerid][6], 1);
TextDrawSetSelectable(PublicTD[playerid][6], 0);

PublicTD[playerid][7] = TextDrawCreate(320.000000, 430.000000, "2026 (c) Todos los derechos reservados");
TextDrawFont(PublicTD[playerid][7], 2);
TextDrawLetterSize(PublicTD[playerid][7], 0.191666, 0.899999);
TextDrawTextSize(PublicTD[playerid][7], 0.000000, 640.000000);
TextDrawSetOutline(PublicTD[playerid][7], 1);
TextDrawSetShadow(PublicTD[playerid][7], 0);
TextDrawAlignment(PublicTD[playerid][7], 2);
TextDrawColor(PublicTD[playerid][7], 1717987071);
TextDrawBackgroundColor(PublicTD[playerid][7], 255);
TextDrawBoxColor(PublicTD[playerid][7], 50);
TextDrawUseBox(PublicTD[playerid][7], 0);
TextDrawSetProportional(PublicTD[playerid][7], 1);
TextDrawSetSelectable(PublicTD[playerid][7], 0);

PublicTD[playerid][9] = TextDrawCreate(320.000000, 180.000000, "Nombre_Usuario");
TextDrawFont(PublicTD[playerid][9], 1);
TextDrawLetterSize(PublicTD[playerid][9], 0.387499, 1.799998);
TextDrawTextSize(PublicTD[playerid][9], 0.000000, 640.000000);
TextDrawSetOutline(PublicTD[playerid][9], 1);
TextDrawSetShadow(PublicTD[playerid][9], 0);
TextDrawAlignment(PublicTD[playerid][9], 2);
TextDrawColor(PublicTD[playerid][9], -1);
TextDrawBackgroundColor(PublicTD[playerid][9], 255);
TextDrawBoxColor(PublicTD[playerid][9], 50);
TextDrawUseBox(PublicTD[playerid][9], 0);
TextDrawSetProportional(PublicTD[playerid][9], 1);
TextDrawSetSelectable(PublicTD[playerid][9], 0);

PublicTD[playerid][12] = TextDrawCreate(320.000000, 277.000000, "COMENZAR JUEGO");
TextDrawFont(PublicTD[playerid][12], 2);
TextDrawLetterSize(PublicTD[playerid][12], 0.254166, 1.449998);
TextDrawTextSize(PublicTD[playerid][12], 200.000000, 440.000000);
TextDrawSetOutline(PublicTD[playerid][12], 1);
TextDrawSetShadow(PublicTD[playerid][12], 0);
TextDrawAlignment(PublicTD[playerid][12], 2);
TextDrawColor(PublicTD[playerid][12], -1);
TextDrawBackgroundColor(PublicTD[playerid][12], 255);
TextDrawBoxColor(PublicTD[playerid][12], 50);
TextDrawUseBox(PublicTD[playerid][12], 0);
TextDrawSetProportional(PublicTD[playerid][12], 1);
TextDrawSetSelectable(PublicTD[playerid][12], 1);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
